bluebird-sept-2020/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #? RESTFUL
  # verb 'path', to: 'controller#action'
  # get '/chirps', to: 'chirps#index'
  # get '/chirps/:id', to: 'chirps#show' # /chirps/12
  # post '/chirps', to: 'chirps#create'
  # patch '/chirps/:id', to: 'chirps#update'
  # delete '/chirps/:id', to: 'chirps#destroy'

  #! NOT RESTFUL
  # get '/chirps/search/:query', to: 'chirps#search'

  # resources :name_of_resource, options hash
  resources :chirps, except: [:new, :edit]
  # resources :chirps, only: [:index, :show, :create, :update, :destroy]

  resources :users
end

bluebird-sept-2020/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :bigint           not null, primary key
#  username   :string           not null
#  email      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  age        :integer          not null
#
class User < ApplicationRecord 
    validates :username, :email, :age, presence: true 
    validates :username, :email, uniqueness: true 

    # associations
    has_many :chirps, # what you want to name association
        primary_key: :id, # from this class
        foreign_key: :author_id, # from other class
        class_name: :Chirp # other class
    
    has_many :likes,
        primary_key: :id,
        foreign_key: :liker_id,
        class_name: :Like 
    
    has_many :liked_chirps,
        through: :likes, # must be association name from this class!!
        source: :chirp # must be association name!!


    #* User Queries:
    ## The following queries are being typed here mainly as a resource for you.
    
    #? Find all instructors between the ages of 90 to 100 inclusive

    # User.find_by # only one object returned
    User.where("age BETWEEN 90 AND 100") # inclusive
    User.where(age: 90..100) # inclusive

    #? Find all users that are not JavaScript affiliated (use where not)

    User.where.not("political_affiliation = 'JavaScript'")

    #? Find all instructors in this list and order by ascending
    instructors = ["mish_mosh", "wakka_wakka", "jen_ken_intensifies"]

    # User.where.in(["mish_mosh", "wakka_wakka", "jen_ken_intensifies"]).order("username")
    User.where("username IN (?)", instructors).order("username")
    User.where(username: instructors).order("username") # Rails MAGIC
    
end

bluebird-sept-2020/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
        # render json: users
        render :index
    end

    def show
        @user = User.find(params[:id])
        # render json: user
        render :show
    end

    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)
        
        if @user.save
            redirect_to user_url(@user)
        else
            # render json: user.errors.full_messages, status: 422
            render :new
        end
    end

    def edit
        @user = User.find(params[:id])
        render :edit
    end

    def update
        @user = User.find(params[:id])

        if @user.update(user_params)
            redirect_to user_url(@user)
        else
            render json: user.errors.full_messages, status: 422
        end
    end

    def destroy
        @user = User.find(params[:id])

        @user.destroy
        redirect_to users_url 
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :age)
    end
end

bluebird-sept-2020/app/views/layouts/users/_form.html.erb
<% if type == 'new' %>
    <% action_url = users_url %>
    <% button_text = 'Create User'%>
<% else %>
    <% action_url = user_url(user) %>
    <% button_text = 'Edit User'%>
<% end %>


<form action="<%= action_url %>" method="POST">
    <% if type == 'edit' %>
        <input type="hidden" name='_method' value='PATCH'>
    <% end %>


    <label>Username:
        <input type="text" name="user[username]" value="<%@user.username%>">
    </label>

    <label>Age:
        <input type="text" name="user[age]" value="<%@user.age%>">
    </label>

    <label>Email:
        <input type="text" name="user[email]" value="<%@user.email%>">
    </label>

    <input type="submit" value="<%button_text%>%">

</form>

bluebird-sept-2020/app/views/layouts/users/_user_html.erb
<%# no instance varialbes in partials  %>

<% if action == 'show' %>
    <a href="<%= users_url %>%">Users Index Link</a>
<% else %>
    <a href="<%= user_url(user) %>%">Users Show Link</a>
<% end %>


<ul class="user-attributes">
    <li><%= user.username %></li>
    <li><%= user.age %></li>
    <li><%= user.email %></li>
</ul>

bluebird-sept-2020/app/views/layouts/users/edit.html.erb
<h1>Edit up a user</h1>

<%= render 'form', user: @user, type: 'new' %>

<!--
<form action="<%= user_url(@user) %>" method="POST">

    <input type="hidden" name="_method" value="PATCH">

    <label>Username:
        <input type="text" name="user[username]" value="<%@user.username%>">
    </label>

    <label>Age:
        <input type="text" name="user[age]" value="<%@user.age%>">
    </label>

    <label>Email:
        <input type="text" name="user[email]" value="<%@user.email%>">
    </label>

    <input type="submit" value="Edit User">

</form>
-->

bluebird-sept-2020/app/views/layouts/users/index.html.erb
<h1>Here are all of our Users</h1>
<a href="<%= new_user_url %>">Create a User</a>

<ul>
    <% @users.each do |user|  %>
        <li class="user">
            <!--<ul class="user-attributes">
                <li><%#= user.username %></li>
                <li><%#= user.age %></li>
                <li><%#= user.email %></li>
            </ul>
            -->
                               <!--user: is from partial, user is the user in the do block --> 
            <%= render 'user', user: user, action: 'index' %>
        </li>
    <% end %>
</ul>

bluebird-sept-2020/app/views/layouts/users/new.html.erb
<h1>Sign up a user</h1>

<%= render 'form', user: @user, type: 'new' %>


<!--
<form action="<%= users_url %>" method="POST">
    <label>Username:
        <input type="text" name="user[username]" value="<%@user.username%>">
    </label>

    <label>Age:
        <input type="text" name="user[age]" value="<%@user.age%>">
    </label>

    <label>Email:
        <input type="text" name="user[email]" value="<%@user.email%>">
    </label>

    <input type="submit" value="Create User">

</form>

-->

bluebird-sept-2020/app/views/layouts/users/show.html.erb
<h1>THIS BE THE USERS SHOW</h1>

<!--
<ul>
    <li><%= @user.username  %></li>
    <li><%= @user.age %></li>
    <li><%= @user.email %></li>
</ul>
-->
<%= render 'user', user: @user, action: 'show' %>
<a href="<%= edit_user_url(@user) %>">Edit this User</a>

<form action="<%= user_url(@user) %>" method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="<%= 'Bye Bye' + @user.username %>">
</form>