Cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats 

end

Cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Cats/app/models/cat.rb
require 'action_view'

# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper
    validates :name, :birth_date, :color, :sex, :description, presence: true

    COLORS = ['Orange', 'White', 'Black', 'Calico', 'Tabby', 'Brown']

    has_many :rental_requests,
        foreign_key: :cat_id,
        class_name: :CatRentalRequests

    def age
        time_ago_in_words(birth_date)
    end
end

Cats/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint           not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class CatRentalRequest < ApplicationRecord
    validates :cat_id, :start_date, :end_date, :status, presence: true

    belongs_to :cat,
        foreign_key: :cat_id,
        class_name: :Cat,
        dependent: :destroy

    
end

Cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.find_by(id: params[:id])
        render :show
    end

    def new
        @cat = Cat.new
        render :new
    end

    def create
        @cat = Cat.new(cats_params)

        if @cat.save
            redirect_to cat_url(@cat)
        else
            render :new
        end
    end

    def edit
        @cat = Cat.find_by(id: params[:id])
        render :edit
    end

    def update
        @cat = Cat.find_by(id: params[:id])
        if @cat.update(cats_params)
            redirect_to cat_url(@cat)
        else
            render :edit
        end
    end

    private

    def cats_params
        params.require(:cat).permit(:name, :sex, :color, :birth_date, :description)
    end


end

Cats/app/helpers/application_helper.rb
module ApplicationHelper
end

Cats/app/views/cats/_form.html.erb
<% if type == "new" %>
    <% action_url = cats_url %>
    <% button_text = 'Create Cat!' %>
<% else %>
    <% action_url = cat_url(@cat) %>
    <% button_text = 'Edit Cat!' %>
<% end %>


<form action="<%= action_url %>" method="POST">
    <% if type == "edit" %>
    <input type="hidden" name="_method" value="PATCH">
    <% end %>
    
    <label>Name:
        <input type="text" name="cat[name]" value="<%= @cat.name %>">
    </label>

    <br><br>

    <label for="sex">Sex:</label>
    <label for="male">Male</label>
    <input type="radio" name="cat[sex]" id="male" value= "M" <%= @cat.sex == 'M' ? "checked" : '' %> >
    <label for="female">Female</label>
    <input type="radio" name="cat[sex]" id="female" value= "F" <%= @cat.sex == 'F' ? "checked" : '' %>>
 

    <br><br>

    <label for="colors">Choose A Color:</label>
    <select name="cat[color]">
        <option disabled <%= type == 'new' ? "selected" : '' %>>--select a color--</option>
        <% Cat::COLORS.each do |color| %>
            <option value="<%= color %>" <%= (@cat.color == color) ? "selected" : '' %>> <%= "#{color}" %> </option>
        <% end %>
    </select>

    <br><br>

    <label>Birthday:
        <input type="date" name="cat[birth_date]" value="<%= @cat.birth_date %>">
    </label>

    <br><br>

    <label for="description">Description:
        <textarea name="cat[description]" id="description" ><%= @cat.description%></textarea>
    </label>

    <br><br>

    <input type="submit" value= "<%= button_text%>">

</form>

Cats/app/views/cats/edit.html.erb
<h1>Edit Cat</h1>

<%= render 'form', cat: @cat, type: 'edit' %>

<!--<form action="<%#= cat_url(@cat) %>" method="POST">
    <input type="hidden" name="_method" value="PATCH">
    <label>Name:
        <input type="text" name="cat[name]" value="<%#= @cat.name %>">
    </label>

    <br><br>

    <label for="sex">Sex:</label>
    <label for="male">Male</label>
    <input type="radio" name="cat[sex]" id="male" value= "M" <%#= @cat.sex == 'M' ? "checked" : '' %> >
    <label for="female">Female</label>
    <input type="radio" name="cat[sex]" id="female" value= "F" <%#= @cat.sex == 'F' ? "checked" : '' %>>
 

    <br><br>

    <label for="colors">Choose A Color:</label>
    <select name="cat[color]">
        <option disabled>--select a color--</option>
        <%# Cat::COLORS.each do |color| %>
            <option value="<%#= color %>" <%#= (@cat.color == color) ? "selected" : '' %>> <%#= "#{color}" %> </option>
        <% #end %>
    </select>

    <br><br>

    <label>Birthday:
        <input type="date" name="cat[birth_date]" value="<%#= @cat.birth_date %>">
    </label>

    <br><br>

    <label for="description">Description:
        <textarea name="cat[description]" id="description" ><%#= @cat.description%></textarea>
    </label>

    <br><br>

    <input type="submit" value="Edit Cat!">

</form>-->

Cats/app/views/cats/index.html.erb
<h1>All The Cats!</h1>

<ul>
    <% @cats.each do |cat| %>
        <li>
            <a href="<%= cat_url(cat) %>"><%= "#{cat.name}" %></a>
        </li>
    <% end %>

</ul>

Cats/app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'form', cat: @cat, type: 'new' %>

<!--<form action="<%#= cats_url %>" method="POST">
    <label>Name:
        <input type="text" name="cat[name]" value="<%#= @cat.name %>">
    </label>

    <br><br>

    <label for="sex">Sex:</label>
    <label for="male">Male</label>
    <input type="radio" name="cat[sex]" id="male" value= "M">
    <label for="female">Female</label>
    <input type="radio" name="cat[sex]" id="female" value= "F">
 

    <br><br>

    <label for="colors">Choose A Color:</label>
    <select name="cat[color]">
        <option selected disabled>--select a color--</option>
        <%# Cat::COLORS.each do |color| %>
            <option value="<%#= color %>"><%#= "#{color}" %></option>
        <% #end %>
    </select>

    <br><br>

    <label>Birthday:
        <input type="date" name="cat[birth_date]" value="<%#= @cat.birth_date %>">
    </label>

    <br><br>

    <label for="description">Description:
        <textarea name="cat[description]" id="description" >
        <%#= @cat.description%>
        </textarea>
    </label>

    <br><br>

    <input type="submit" value="Create Cat!">

</form>-->

Cats/app/views/cats/show.html.erb
<a href=" <%= cats_url %> ">99 Cats</a>

<h1><%= @cat.name %></h1>

<table>
    <tr>
        <th>Attribute</th>
        <th>Value</th>
    </tr>
    <tr>
        <td>Age</td>
        <td><%= @cat.age %></td>
    </tr>
    <tr>
        <td>Birth Date</td>
        <td><%= @cat.birth_date %></td>
    </tr>
    <tr>
        <td>Color</td>
        <td><%= @cat.color %></td>
    </tr>
    <tr>
        <td>Sex</td>
        <td><%= @cat.sex %></td>
    </tr>
</table>

<br><br>

<a href="<%= edit_cat_url(@cat) %>">Edit Cat</a>

Cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>